// <auto-generated />
using System;
using MarketData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketData.Migrations
{
    [DbContext(typeof(MarketDataContext))]
    [Migration("20260217133803_AddModelConfigs")]
    partial class AddModelConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MarketData.Models.FlatConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("FlatConfigs");
                });

            modelBuilder.Entity("MarketData.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TickIntervalMillieconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("MarketData.Models.MeanRevertingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Dt")
                        .HasColumnType("REAL");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kappa")
                        .HasColumnType("REAL");

                    b.Property<double>("Mean")
                        .HasColumnType("REAL");

                    b.Property<double>("Sigma")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("MeanRevertingConfigs");
                });

            modelBuilder.Entity("MarketData.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instrument")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("MarketData.Models.RandomAdditiveWalkConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalkStepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("RandomAdditiveWalkConfigs");
                });

            modelBuilder.Entity("MarketData.Models.RandomMultiplicativeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mean")
                        .HasColumnType("REAL");

                    b.Property<double>("StandardDeviation")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId")
                        .IsUnique();

                    b.ToTable("RandomMultiplicativeConfigs");
                });

            modelBuilder.Entity("MarketData.Models.FlatConfig", b =>
                {
                    b.HasOne("MarketData.Models.Instrument", "Instrument")
                        .WithOne("FlatConfig")
                        .HasForeignKey("MarketData.Models.FlatConfig", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MarketData.Models.MeanRevertingConfig", b =>
                {
                    b.HasOne("MarketData.Models.Instrument", "Instrument")
                        .WithOne("MeanRevertingConfig")
                        .HasForeignKey("MarketData.Models.MeanRevertingConfig", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MarketData.Models.RandomAdditiveWalkConfig", b =>
                {
                    b.HasOne("MarketData.Models.Instrument", "Instrument")
                        .WithOne("RandomAdditiveWalkConfig")
                        .HasForeignKey("MarketData.Models.RandomAdditiveWalkConfig", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MarketData.Models.RandomMultiplicativeConfig", b =>
                {
                    b.HasOne("MarketData.Models.Instrument", "Instrument")
                        .WithOne("RandomMultiplicativeConfig")
                        .HasForeignKey("MarketData.Models.RandomMultiplicativeConfig", "InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("MarketData.Models.Instrument", b =>
                {
                    b.Navigation("FlatConfig");

                    b.Navigation("MeanRevertingConfig");

                    b.Navigation("RandomAdditiveWalkConfig");

                    b.Navigation("RandomMultiplicativeConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
